== Plugin configuration

After downloading the plugin, you just have to activate it, there is no additional configuration at this level.

== Notion immédiate

C'est une notion très importante sur le plugin alarme et il est important de bien la bien comprendre. Pour schématiser c'est comme si vous aviez 2 alarmes, la première : l'alarme immédiate qui ne tient pas compte des délais de déclenchement (attention elle prend bien en compte les délais d'activation) et une 2ème alarme qui, elle, prend en compte les délais de déclenchement.

*Pourquoi cette notion immédiate ?*

Cette notion immédiate permet de déclencher des actions bien spécifiques. Par exemple : vous rentrez chez vous et vous n'avez pas désactiver l'alarme, avant de déclencher la sirène il peut être bon de diffuser un message rappellant de bien désactiver l'alarme et si ce n'est pas fait 1 minute plus tard (délai d'activation de 1 minute donc) d'activer la sirène.

Cette notion se retrouve dans différents types d'actions, à chaque fois son principe sera détaillé.

== Equipements

La configuration des équipements Alarme est accessible à partir du menu plugin (dans sécurité). 

Une fois une alarme ajoutée vous vous retrouvez avec : 

Alarm Name : Choose a name for your alarm
* *Parent Object* : means the parent object the equipment depend
Category : This is the category of the equipment (generally "security" for alarms)
Enable : To enable your equipment
Visible : Make your equipment visible on the Dashboard
Permanently Enable : Make your alarm permanently enable (generally for Fire or Flood alarms)
* *Armement visible* : permet de rendre visible ou non la commande d'armement de l'alarme sur le widget,
* *Statut immédiat visible* : permet de rendre le statut immédiat de l'alarme visible (voir plus bas pour l'explication),
* *Historiser état et statut de l'alarme* : permet d'historiser ou non l'état et le statut de l'alarme.

[TIP]
Pour chaque action il est possible de spécifier le mode dans lequel elle doit s'executer ou dans tous les modes

== Areas

Partie principale de l'alarme. C'est ici que vous configurez les différentes zones et les actions (immédiates et différées par zone, à noter qu'il est aussi possible de les configurer globalement) à faire en cas de déclenchement. Une zone peut aussi bien être volumétrique (pour la journée par exemple) que périmétrique (pour la nuit) ou aussi des zones de la maison (garage, chambre, dépendances....). 

A button at the top right allows you to add as many as you want.

[TIP]
Il est possible d'éditer le nom de la zone en cliquant sur le nom de celle-ci (en face du label "Nom de la zone").

A zone got several elements :  
-trigger,
- immediate action
-action.

=== Trigger

A trigger is a binary command. When its value is 1, it triggers the alarm. It is possible to invert the trigger if you want that value 0 triggers the alarm. Simply put "invert" on YES
Once you chose the trigger, you can set an activation delay (It's not possible to choose less than 1 minute). This delay lets you for example, go out of your home after alarm activation. Be careful, some of motion sensors keep the value 1 for a few minutes, so you need to consider it for the activation delay setting
Ensuite vous avez le délai de déclenchement, à la difference du délai d'activation qui n'a lieu que une fois lors de l'activation de l'alarme, celui-ci est mis en place après chaque déclenchement d'un capteur. La cinématique est la suivante lors du déclenchement du capteur (ouverture de porte, détection de présence), si les délais d'activation sont passés,  l'alarme va déclencher les actions immédiates mais va attendre que le délai d'activation soit fini avant de déchencher les actions.
Finally you have the "invert" button, to invert trigger status (0 instead of 1).

Petit exemple pour bien comprendre : sur le premier déclencheur (#[Salon][Oeil][Présence]#) j'ai ici un délai d'activation de 5 minutes et de déclenchement de 1 minute. Cela veut dire que lorsque j'active l'alarme, pendant les 5 premières minutes aucun déclenchement de l'alarme ne pourra avoir lieu à cause de ce capteur. Passé ce délai de 5 minutes, si un mouvement est détecté par le capteur, l'alarme va attendre 1 minute (le temps de me laisser désactiver l'alarme) avant de déclencher les actions. Si j'avais eu des actions immédiates celles-ci se seraient déclenchées immédiatement sans attendre la fin du délai d'activation, les actions non immédiates auraient eu lieu après (1 minute après les actions immédiates).


===  Immediate Action

Comme décrit plus haut, ce sont des actions qui se déclenchent dès le déclenchement en ne tenant pas compte du délai de déclenchement (mais en tenant compte quand même du délai d'activation). Vous avez juste à sélectionner la commande d'action voulue puis en fonction de celle-ci remplir les paramètres d'exécution.

[NOTE]
Lorsque plusieures zones sont déclenchées successivement, seules les actions immédiates de la 1ere zone déclenchée sont exécutées.

== Modes

Les modes sont assez simples à configurer, il suffit juste d'indiquer les zones actives en fonction du mode.

[TIP]
Il est possible de renommer le mode en cliquant sur le nom de celui-ci (en face du label "Nom du mode").

[NOTE]
Lors du renommage d'un mode, il faut sur le widget de l'alarme recliquer sur le mode en question pour une prise en compte complete (sinon jeedom reste sur l'ancien mode)

[IMPORTANT]
You need to create at least one mode, and set it "zones". If not, your alarm will not work correctly

== Activation OK

Cette partie permet de définir les actions à faire suite à une activation de l'alarme. Ici encore, vous retrouverez la notion immédiate qui représente les actions à faire toute de suite après armement de l'alarme, ensuite viennent les actions d'activation qui elles sont exécutées après les délais de déclenchement. 

Dans l'exemple, ici j'allume par exemple une lampe en rouge pour signaler que l'armement a bien été pris en compte et je l'éteinds une fois l'armement complet (car normalement il n'y a plus personne dans le périmètre de l'alarme, sinon ça la déclenche).

[IMPORTANT]
Les actions d'activation OK ne prennent pas en compte les délais d'activation. Si vous avez un délai sur l'activation d'un capteur d'ouverture, même si votre porte est ouverte les actions d'activation seront exécutées.

== Enable KO

Ces actions sont exécutées si un capteur est déclenché et que celui-ci n'a pas de délai d'activation.

== Déclenchement

Permet de configurer les actions globals à faire lors d'un déclenchement de l'alarme. Vous n'etes pas obliger d'en ajouter si vous avez configurez des actions spécifique par zone.

== Disable OK

These actions are executed when the alarm is disabled and not triggered. For example, you get back to your home , open the door triggers the alarm, but you set a trigger delay on the sensor and you turn off the alarm before the end of this delay , disable OK actions will be executed. But If you stopped the alarm after the end of trigger delay disable OK actions won't be executed.

== Reset

Cette partie vous permet de définir les actions à faire lorsque l'alarme est déclenchée puis désactivée. Ici aussi il y a des actions immédiates et différées. Voici un exemple : vous rentrez chez vous, les délais d'activation sont passés, mais en ouvrant la porte cela déclenche l'alarme. Si vous la désactiver (avant les délais de déclenchement) alors les actions de réinitialisation immédiate seront exécutées, mais pas celles de réinitialisation normale. Si vous la désactivez après les délais de déclenchement, alors les actions de réinitialisation immédiate et normale seront exécutées.