== Configuración del plugin

Después de descargar el plugin, simplemente hay que activarlo, no hay ninguna otra configuración adicional aquí.

== Concepto inmediato

Es un concepto muy importante en el plugin de alarma y es importante entenderlo bien. En pocas palabras es como si tuvieras 2 alarmas, la primera: alarma inmediata que no conlleva retrasos de activación (**atención ella tarda mucho en tiempos de activación de cuenta**) y  la segunda, que conlleva retardo en la comunicación tras el disparo o activación.

*¿Por qué este concepto de inmediata?*

Es concepto es el plazo inmediato para activar acciones específicas. Por ejemplo: llega a casa y si no desconecta la alarma, antes de accionar la sirena, puede ser bueno para difundir un mensaje recordando que debe desconectar la alarma y si no se hace 1 minuto más tarde (retardo de 1 minuto así) se activa la sirena.

Este concepto se encuentra en diferentes tipos de acción, à chaque fois son principe sera détaillé.

== Equipements

La configuration des équipements Alarme est accessible à partir du menu plugin (dans sécurité). 

Une fois une alarme ajoutée vous vous retrouvez avec : 

* *Nombre del dispositivo de la alarma* : nombre de la alarma.
* *Objeto primario* : indica el objeto primario que pertenece al equipo.
* *Categoría* : la categoría del dispositivo (seguridad en general para una alarma).
* *Activar* : permite activar el dispositivo.
* *Visible* : hace visible el dispositivo en el Dashboard.
* *Activo permanentemente* : indica que la alarma esta activa permanentemente (por ejemplo una alarma de detección de incendio).
* *Armamento visible* : permite hacer visible o no la ordem de activación de la alarma en el widget.
* *Estado inmediato visible* : permite hacer visible el estado inmediato de la alarma (véase abajo la explicación).
* * Histórico del estatus del estado de la alarma *: permite registrar el estatus o el estado de la alarma.

[TIP]
Pour chaque action il est possible de spécifier le mode dans lequel elle doit s'executer ou dans tous les modes

== Zonas

Partie principale de l'alarme. C'est ici que vous configurez les différentes zones et les actions (immédiates et différées par zone, à noter qu'il est aussi possible de les configurer globalement) à faire en cas de déclenchement. Une zone peut aussi bien être volumétrique (pour la journée par exemple) que périmétrique (pour la nuit) ou aussi des zones de la maison (garage, chambre, dépendances....). 

Un botón en la parte superior derecha permite añadir tantas como quieras.

[TIP]
Es posible editar el nombre de la zona haciendo clic en el nombre del mismo (encima de la etiqueta "Nombre de la zone").

Una zona se compone de diferentes elementos: 
-Disparador,
-acción inmediata,
-acción.

=== Disparador

Un disparador es una orden binaria, que cuando el valor es 1 se activará la alarma. Es posible revertir el disparador, para que sea el estado 0 del sensor el que dispare la alarma, poniendo "invertir" en SI.
Una vez que haya escogido el disparador, puede especificar un retraso de la activación en minutos (no es posible indicar por debajo del minuto). Esto permite por ejemplo, si quieres activar la alarma antes de que salgas de casa, no active la alarma antes de un minuto (El tiempo que tardes en salir). Otro caso, algunos sensores de movimiento permanecen en modo activado (valor 1) por un período de tiempo, incluso si no hay ninguna detección, por ejemplo, 4 minutos, así que es recomendable cambiar la activación de estos sensores a 4 o 5 min para que la alarma no se disparé inmediatamente después de la activación.
Una vez se tiene el tiempo de retardo, la diferencia de retardo de la activación que indicó una vez cuando la alarma se activa, se aplica después de disparar cada sensor. La operación es la siguiente: El sensor (apertura de la puerta, detección de presencia), si los retardos de activación se sobrepasan, la alarma disparará las acciones inmediatas, la alarma activará una acción inmediata pero esperará hasta que el retardo expire para la activación de las acciones.
Por último tienes el botón "Invertir" que permite invertir el disparador del estado del sensor (0 1).

Un pequeño ejemplo para comprenderlo: sobre el primer disparador (#[Salon][Oeil][Présence]#) aquí tengo un retraso de de activación de 5 minutos y  de disparo de 1 . Esto significa que cuando activo la alarma, durante los primeros 5 minutos no hay activación, la alarma no se disparará desde este sensor. Después de 5 minutos, si hay movimiento detectado por el sensor, la alarma esperará 1 minuto (el tiempo que necesito para desactivar la alarma) antes de ser disparada. Si tuviera acciones inmediatas se activará inmediatamente, sin esperar a que termine el retardo de activación, las acciones no inmediatas no se activaran ( hasta 1 minuto después de la acción inmediata).


=== Acción inmediata

Como se describió anteriormente, estas son acciones que se activan tan pronto haya un disparo,  no teniendo en cuenta el tiempo de retardo (pero teniendo en cuenta incluso cuando se demora la activación). Sólo tienes que seleccionar el comando de acción deseada y por lo tanto completar los parámetros de ejecución.

[NOTA]
Cuando varias zonas se activan sucesivamente, sólo las acciones inmediatas de la 1 º zona activada serán ejecutadas.

== Modos

Los modos son bastante simples de configurar, simplemente especifique áreas activas dependiendo de la modalidad.

[TIP]
Es posible cambiar el modo pulsando sobre el nombre del mismo (frente a la etiqueta "Nombre").

[NOTA]
Al retomar un modo, desde el widget de la alarma, haz click sobre el modo en cuestión para una toma completa (de lo contrario jeedom permanece en el modo antiguo)

[IMPORTANTE]
Necesitamos obligatoriamente crear al menos un modo y asignar zonas , si no alarma no funciona.

== Activación OK

Esta sección permite definir las acciones que se harán después de la activación de la alarma. Aquí encontrará una idea rápida, que representa las acciones que se realizan inmediatamente después de la activación de la alarma, después vienen las acciones de activación que son ejecutadas con retardos programados. 

En el ejemplo, una vez finalizado el armamento, se enciende una bombilla en rojo para indicar que la alarma se armó correctamente (normalmente, indicar que no hay nadie más en el perímetro, de lo contrario se arma)

[IMPORTANTE]
Las acciones de activiación OK no tienen en cuenta en la activación los retardos. Si tienes un retardo de activación en un sensor abierto, incluso si la puerta esta abierta, la acción de activación será ejecutada.

== Activation KO

Ces actions sont exécutées si un capteur est déclenché et que celui-ci n'a pas de délai d'activation.

== Déclenchement

Permet de configurer les actions globals à faire lors d'un déclenchement de l'alarme. Vous n'etes pas obliger d'en ajouter si vous avez configurez des actions spécifique par zone.

== Desactivación OK

Estas acciones se realizan cuando la alarma es desactivada. por ejemplo, llegua a casa, abre la puerta y activa la alarma, pero le puso un tiempo de retardo en el sensor y desarmó la alarma antes del final del tiempo de retardo se realizarán las acciones de desactivación OK. Si por el contrario detienes la alarma después del tiempo de retardo, no se hubiera ejecutado.

== Reinicialización

Esta sección le permite definir las acciones cuando la alarma se ha disparado y es desactivada. Aquí también hay acciones inmediatas y diferidas. Por ejemplo: vuelves a casa, los tiempos de activación han pasado, pero al abrir la puerta se dispara la alarma. Si la desactivas (antes de tiempo del disparo) entonces se realizarán las acciones de reinialización inmediato, pero no los de reinialización normal. Si desactivas después del disparo,  entonces se realizarán las acciones de reinialización inmediata y normal.